const MATT_PARAMS = ['matt_word', 'matt_tool'];

function readParamsFromUrl(parsed, names) {
  const found = {};
  names.forEach((name) => {
    if (parsed.searchParams.has(name)) {
      found[name] = parsed.searchParams.get(name);
    }
  });

  if (parsed.hash.length > 1 && parsed.hash.includes('=')) {
    const hashParams = new URLSearchParams(parsed.hash.slice(1));
    names.forEach((name) => {
      if (found[name] === undefined && hashParams.has(name)) {
        found[name] = hashParams.get(name);
      }
    });
  }

  return found;
}

/**
 * Parses a single real affiliate link (pasted by the user, generated by
 * Mercado Livre's own "central de afiliados" / "Barra de afiliados") to
 * record what format that account's links use. This is a read-only
 * observation tool: it never feeds back into generateAffiliateLink() and
 * must never be used to construct a link for a different product.
 *
 * Mercado Livre's own help pages state that a link which didn't go through
 * their official generator earns no commission, so guessing at a formula
 * from these values would very likely produce a non-functional (or
 * account-risking) link — see docs/nova-versao-mvp-mercadolivre.md section 5.
 */
function detectAffiliateLinkFormat(sampleLink) {
  const raw = String(sampleLink || '').trim();

  let parsed;
  try {
    parsed = new URL(raw);
  } catch (error) {
    return { format: 'invalido', detectedMattWord: null, detectedMattTool: null, detectedTag: null };
  }

  const hostname = parsed.hostname.toLowerCase();
  if (hostname === 'meli.la' || hostname.endsWith('.meli.la')) {
    return { format: 'meli_la_short', detectedMattWord: null, detectedMattTool: null, detectedTag: null };
  }

  const mattValues = readParamsFromUrl(parsed, MATT_PARAMS);
  if (mattValues.matt_word || mattValues.matt_tool) {
    return {
      format: 'long_form_matt',
      detectedMattWord: mattValues.matt_word || null,
      detectedMattTool: mattValues.matt_tool || null,
      detectedTag: null,
    };
  }

  // "tag" is a speculative, generic affiliate-URL pattern seen on other
  // platforms — NOT a confirmed Mercado Livre parameter name. Detected only
  // for reference; do not treat its presence as validating anything.
  const tagValues = readParamsFromUrl(parsed, ['tag']);
  if (tagValues.tag) {
    return { format: 'long_form_tag', detectedMattWord: null, detectedMattTool: null, detectedTag: tagValues.tag };
  }

  return { format: 'desconhecido', detectedMattWord: null, detectedMattTool: null, detectedTag: null };
}

module.exports = { detectAffiliateLinkFormat };
