// Generic marketing/tracking params that are safe to strip from almost any link.
// Deliberately conservative: platform-specific tracking parameters are NOT
// stripped here because we don't know (and must not assume) which ones the
// Mercado Livre affiliate program relies on for attribution. Confirm with the
// platform's official documentation/panel before expanding this list.
const GENERIC_TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'fbclid',
  'gclid',
  'igshid',
];

// Mercado Livre affiliate attribution params, confirmed by direct observation
// (a real link generated by the platform's own "central de afiliados" uses
// the meli.la short domain; the long-form equivalent shared by other
// affiliates in source groups carries these params — matt_word/matt_tool
// identify the affiliate/tool, ref carries an opaque per-click token).
// These MUST be stripped from clean_link: leaving another affiliate's ref
// on a link we republish would route any resulting commission to THEM, not
// to the user. Still worth confirming against official docs if available,
// but treated as a hard requirement here given the commercial risk.
const PLATFORM_AFFILIATE_PARAMS = {
  mercado_livre: [
    'matt_word',
    'matt_tool',
    'matt_tool_id',
    'matt_event_ts',
    'matt_d2id',
    'matt_tracing_id',
    'matt_ignore',
    'ref',
    'forceInApp',
    'skipInApp',
  ],
};

const REQUEST_TIMEOUT_MS = 8000;
const USER_AGENT = 'Mozilla/5.0 (compatible; OfferReviewBot/0.1; +manual-review-tool)';

function detectPlatform(url, platformDomains) {
  let hostname;
  try {
    hostname = new URL(url).hostname.toLowerCase();
  } catch (error) {
    return null;
  }

  for (const [platform, domains] of Object.entries(platformDomains)) {
    if (domains.some((domain) => hostname === domain || hostname.endsWith(`.${domain}`))) {
      return platform;
    }
  }
  return null;
}

function stripParamsFromQueryLike(queryLike, paramNames) {
  const params = new URLSearchParams(queryLike);
  paramNames.forEach((param) => params.delete(param));
  return params.toString();
}

/**
 * Removes generic marketing params and (when the platform is known) that
 * platform's affiliate attribution params from a URL's query string. Also
 * scrubs the same param names from the URL fragment when the fragment looks
 * like a query string itself (key=value&key2=value2) — some Mercado Livre
 * links carry attribution there instead of (or in addition to) the query
 * string, so cleaning only the query would leave someone else's tracking in
 * place.
 */
function stripTrackingParams(url, platform) {
  try {
    const parsed = new URL(url);
    const paramsToStrip = [...GENERIC_TRACKING_PARAMS, ...(PLATFORM_AFFILIATE_PARAMS[platform] || [])];

    paramsToStrip.forEach((param) => parsed.searchParams.delete(param));

    if (parsed.hash.length > 1 && parsed.hash.includes('=')) {
      const cleanedHash = stripParamsFromQueryLike(parsed.hash.slice(1), paramsToStrip);
      parsed.hash = cleanedHash ? `#${cleanedHash}` : '';
    }

    return parsed.toString();
  } catch (error) {
    return url;
  }
}

/**
 * The URL fragment (everything after "#") is never sent to the server, so
 * following redirects with fetch() always yields a final URL stripped of it
 * — even when the fragment carries attribution data. Some Mercado Livre
 * links observed in practice put affiliate/session tracking params there
 * (e.g. matt_tool_id, source=affiliate-profile), so silently dropping the
 * fragment while "cleaning" a link could destroy real commission tracking.
 * This reattaches the original fragment to a resolved URL when the
 * resolved URL didn't already provide one of its own.
 */
function preserveFragment(resolvedUrl, originalUrl) {
  try {
    const original = new URL(originalUrl);
    if (!original.hash) {
      return resolvedUrl;
    }
    const resolved = new URL(resolvedUrl);
    if (!resolved.hash) {
      resolved.hash = original.hash;
    }
    return resolved.toString();
  } catch (error) {
    return resolvedUrl;
  }
}

/**
 * Follows redirects for the given URL and reports whether the final
 * destination responds successfully. This is the MVP's *only* validation:
 * it proves the link is reachable, nothing more. It does NOT confirm price,
 * stock, coupon validity, shipping, seller trustworthiness, or — critically —
 * that any affiliate/commission tracking parameter survived the redirect.
 */
async function resolveFinalUrl(url) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'User-Agent': USER_AGENT },
    });
    if (response.body && typeof response.body.cancel === 'function') {
      response.body.cancel().catch(() => {});
    }
    return {
      ok: response.ok,
      status: response.status,
      finalUrl: response.url || url,
    };
  } catch (error) {
    return {
      ok: false,
      status: null,
      finalUrl: url,
      error: error.name === 'AbortError' ? 'timeout' : error.message,
    };
  } finally {
    clearTimeout(timeout);
  }
}

module.exports = {
  detectPlatform,
  stripTrackingParams,
  resolveFinalUrl,
  preserveFragment,
  PLATFORM_AFFILIATE_PARAMS,
};
